<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HVDIVD00MIS1614" ignored="0" name="BVTwirelineSAflow-1-Firefox" tests="1" failures="1" timestamp="25 Jul 2017 16:16:19 GMT" time="113.734" errors="0">
  <testcase name="test" time="82.019" classname="com.TestCase.Application.BVT.BVTwirelineSAflow">
    <failure type="java.lang.AssertionError" message="Validate user successfully logged in to MyATT">
      <![CDATA[java.lang.AssertionError: Validate user successfully logged in to MyATT
	at com.SupportingFiles.Report.TestPoint(Report.java:442)
	at com.SupportingFiles.LaunchAndLogout.LoginApplication(LaunchAndLogout.java:1144)
	at com.TestCase.Application.BVT.BVTwirelineSAflow.test(BVTwirelineSAflow.java:35)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- BVTwirelineSAflow-1-Firefox -->
